# Generated by Django 4.2.15 on 2024-09-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Fiction', 'Fiction'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Comedy', 'Comedy'), ('SCI-FI', 'SCI-FI')], max_length=200),
        ),
    ]
